const quiz_questions = [
    {
        id: 1,
        topic: "PHISHING", 
        color: "red",
        image: "CyberQuiz.Media/CyberQuiz.Media/questions_icons/ethics.png",
        question: "What is a common sign of a phishing email?",
        options: ["Misspelled sender address","Strong password","Secure website","Two-factor authentication"],
        difficulty: 20,
        hint: "Check for small mistakes in the sender’s details.",
        explanation: "Phishing emails often use fake or misspelled email addresses to trick users.",
    },
    {
        id: 2,
        topic: "PASSWORDS", 
        color: "blue",
        image: "CyberQuiz.Media/CyberQuiz.Media/questions_icons/ethics.png",
        question: "What makes a password strong?",
        options: ["Combination of letters, numbers, and symbols","Your pet’s name","Your birthdate","Only lowercase letters"],
        difficulty: 15,
        hint: "Think about complexity and unpredictability.",
        explanation: "Strong passwords mix uppercase, lowercase, symbols, and numbers to prevent easy guessing.",
    },
    {
        id: 3,
        topic: "MALWARE", 
        color: "green",
        image: "CyberQuiz.Media/CyberQuiz.Media/questions_icons/ethics.png",
        question: "What is malware?",
        options: ["Malicious software designed to harm a system","An antivirus program","A harmless script","A software update"],
        difficulty: 25,
        hint: "The word itself means 'malicious software'.",
        explanation: "Malware includes viruses, worms, and trojans that damage or steal data.",
    },
    {
        id: 4,
        topic: "TWO-FACTOR AUTHENTICATION", 
        color: "orange",
        image: "CyberQuiz.Media/CyberQuiz.Media/questions_icons/ethics.png",
        question: "What does two-factor authentication provide?",
        options: ["An extra layer of security","A faster login","Password recovery","Access without a password"],
        difficulty: 30,
        hint: "It requires more than one verification step.",
        explanation: "2FA adds a second verification step, like a code or fingerprint, making accounts harder to hack.",
    },
    {
        id: 5,
        topic: "SOCIAL ENGINEERING", 
        color: "purple",
        image: "CyberQuiz.Media/CyberQuiz.Media/questions_icons/ethics.png",
        question: "What is the goal of social engineering?",
        options: ["To manipulate people into revealing information","To fix network issues","To test passwords","To train AI systems"],
        difficulty: 40,
        hint: "It targets people, not computers.",
        explanation: "Social engineering tricks users into giving sensitive info through manipulation or deception.",
    },
    {
        id: 6,
        topic: "ANTIVIRUS", 
        color: "teal",
        image: "CyberQuiz.Media/CyberQuiz.Media/questions_icons/ethics.png",
        question: "Why should you keep your antivirus updated?",
        options: ["To detect the latest threats","To reduce internet speed","To uninstall malware","To clear cache"],
        difficulty: 25,
        hint: "New viruses appear every day.",
        explanation: "Updating ensures your antivirus can identify and stop new malware variants.",
    },
    {
        id: 7,
        topic: "WI-FI SECURITY", 
        color: "pink",
        image: "CyberQuiz.Media/CyberQuiz.Media/questions_icons/ethics.png",
        question: "What is the safest Wi-Fi encryption type for home use?",
        options: ["WPA3","WEP","No encryption","Open network"],
        difficulty: 60,
        hint: "It’s the latest standard.",
        explanation: "WPA3 is the most secure Wi-Fi encryption protocol for home networks.",
    },
    {
        id: 8,
        topic: "RANSOMWARE", 
        color: "brown",
        image: "CyberQuiz.Media/CyberQuiz.Media/questions_icons/ethics.png",
        question: "What does ransomware typically do?",
        options: ["Encrypts your files and demands payment","Improves performance","Deletes old data","Sends spam emails"],
        difficulty: 55,
        hint: "It locks your files and asks for money.",
        explanation: "Ransomware encrypts personal files and demands a ransom for decryption.",
    },
    {
        id: 9,
        topic: "DATA PRIVACY", 
        color: "cyan",
        image: "CyberQuiz.Media/CyberQuiz.Media/questions_icons/ethics.png",
        question: "What is the best way to protect your personal data online?",
        options: ["Avoid sharing sensitive info on unsecured sites","Use public Wi-Fi for banking","Store passwords in browsers","Disable all security updates"],
        difficulty: 35,
        hint: "Look for the padlock icon in the browser.",
        explanation: "Unsecured sites (HTTP) can leak data; always use HTTPS and limit shared info.",
    },
    {
        id: 10,
        topic: "EMAIL SECURITY", 
        color: "magenta",
        image: "CyberQuiz.Media/CyberQuiz.Media/questions_icons/ethics.png",
        question: "What should you do if an unknown sender asks for your password?",
        options: ["Ignore or report the email","Reply politely","Send partial info","Click the link to verify"],
        difficulty: 30,
        hint: "Never share credentials through email.",
        explanation: "Legitimate services never request passwords via email.",
    },
    {
        id: 11,
        topic: "SOFTWARE UPDATES", 
        color: "lime",
        image: "CyberQuiz.Media/CyberQuiz.Media/questions_icons/ethics.png",
        question: "Why are software updates important?",
        options: ["They patch security vulnerabilities","They slow your system","They remove data","They install ads"],
        difficulty: 20,
        hint: "They fix more than bugs.",
        explanation: "Updates close known security holes and prevent exploitation.",
    },
    {
        id: 12,
        topic: "BROWSER SAFETY", 
        color: "indigo",
        image: "CyberQuiz.Media/CyberQuiz.Media/questions_icons/ethics.png",
        question: "What should you check before entering your credit card info?",
        options: ["The site has HTTPS","The site looks colorful","The site loads slowly","The price seems high"],
        difficulty: 30,
        hint: "Look for a lock icon.",
        explanation: "HTTPS encrypts data between your browser and the site, keeping it safe.",
    },
    {
        id: 13,
        topic: "ENCRYPTION", 
        color: "yellow",
        image: "CyberQuiz.Media/CyberQuiz.Media/questions_icons/ethics.png",
        question: "What is encryption used for?",
        options: ["Protecting data by converting it into unreadable code","Deleting old files","Speeding up the system","Backing up files"],
        difficulty: 45,
        hint: "It scrambles information.",
        explanation: "Encryption ensures that only authorized users can read the data.",
    },
    {
        id: 14,
        topic: "USB SAFETY", 
        color: "lightblue",
        image: "CyberQuiz.Media/CyberQuiz.Media/questions_icons/ethics.png",
        question: "What should you do before using an unknown USB drive?",
        options: ["Scan it with antivirus","Plug it in immediately","Ignore it","Format it right away"],
        difficulty: 35,
        hint: "It could be infected.",
        explanation: "Unknown USB drives may contain malware; always scan them first.",
    },
    {
        id: 15,
        topic: "PUBLIC WI-FI", 
        color: "darkorange",
        image: "CyberQuiz.Media/CyberQuiz.Media/questions_icons/ethics.png",
        question: "What’s the safest way to use public Wi-Fi?",
        options: ["Use a VPN connection","Access your bank directly","Turn off your firewall","Share files with others"],
        difficulty: 50,
        hint: "Encrypt your traffic even on public networks.",
        explanation: "VPNs protect your data from eavesdropping on open networks.",
    },
    {
        id: 16,
        topic: "CYBERBULLYING", 
        color: "violet",
        image: "CyberQuiz.Media/CyberQuiz.Media/questions_icons/ethics.png",
        question: "What should you do if you experience cyberbullying?",
        options: ["Report and block the user","Respond aggressively","Ignore and delete your account","Share personal info"],
        difficulty: 20,
        hint: "Always involve the platform or authorities if needed.",
        explanation: "Reporting stops harassment and helps prevent future incidents.",
    },
    {
        id: 17,
        topic: "PASSWORD MANAGEMENT", 
        color: "gold",
        image: "CyberQuiz.Media/CyberQuiz.Media/questions_icons/ethics.png",
        question: "Why use a password manager?",
        options: ["To store and generate complex passwords securely","To remember one password","To share passwords","To save time logging in"],
        difficulty: 40,
        hint: "It’s safer than writing them down.",
        explanation: "Password managers encrypt and store passwords securely.",
    },
    {
        id: 18,
        topic: "FIREWALL", 
        color: "darkgreen",
        image: "CyberQuiz.Media/CyberQuiz.Media/questions_icons/ethics.png",
        question: "What is the function of a firewall?",
        options: ["Block unauthorized access to a network","Speed up internet","Store passwords","Update software"],
        difficulty: 45,
        hint: "It acts as a digital gatekeeper.",
        explanation: "Firewalls monitor traffic and block harmful connections.",
    },
    {
        id: 19,
        topic: "BACKUP", 
        color: "coral",
        image: "CyberQuiz.Media/CyberQuiz.Media/questions_icons/ethics.png",
        question: "Why should you regularly back up your files?",
        options: ["To recover data in case of loss","To free up memory","To make files smaller","To share data faster"],
        difficulty: 25,
        hint: "It’s your recovery plan.",
        explanation: "Backups prevent data loss from system failures or ransomware.",
    },
    {
        id: 20,
        topic: "IDENTITY THEFT", 
        color: "salmon",
        image: "CyberQuiz.Media/CyberQuiz.Media/questions_icons/ethics.png",
        question: "How can identity theft be prevented?",
        options: ["Avoid sharing personal details online","Share IDs on social media","Use one password everywhere","Ignore suspicious activity"],
        difficulty: 50,
        hint: "Think before you post.",
        explanation: "Limiting public exposure of personal information reduces identity theft risk.",
    },
    {
        id: 21,
        topic: "COOKIES", 
        color: "turquoise",
        image: "CyberQuiz.Media/CyberQuiz.Media/questions_icons/ethics.png",
        question: "What are website cookies mainly used for?",
        options: ["Storing user preferences","Spreading viruses","Slowing down the site","Encrypting emails"],
        difficulty: 20,
        hint: "They remember things for websites.",
        explanation: "Cookies save preferences or login states, but can also track activity.",
    },
    {
        id: 22,
        topic: "FAKE WEBSITES", 
        color: "maroon",
        image: "CyberQuiz.Media/CyberQuiz.Media/questions_icons/ethics.png",
        question: "How can you spot a fake website?",
        options: ["Misspelled URLs and no HTTPS","Professional design","Fast loading speed","Multiple ads"],
        difficulty: 40,
        hint: "Fake sites often look almost real.",
        explanation: "Check the URL carefully and verify HTTPS before trusting it.",
    },
    {
        id: 23,
        topic: "SOCIAL MEDIA SAFETY", 
        color: "navy",
        image: "CyberQuiz.Media/CyberQuiz.Media/questions_icons/ethics.png",
        question: "What should you avoid posting publicly on social media?",
        options: ["Your address or ID info","Memes","General opinions","Travel photos"],
        difficulty: 25,
        hint: "Personal data can be misused.",
        explanation: "Sensitive info can lead to identity theft or security breaches.",
    },
    {
        id: 24,
        topic: "VPN", 
        color: "olive",
        image: "CyberQuiz.Media/CyberQuiz.Media/questions_icons/ethics.png",
        question: "What does a VPN do?",
        options: ["Encrypts your internet traffic","Increases your data plan","Connects to any Wi-Fi","Disables ads"],
        difficulty: 55,
        hint: "It protects your privacy online.",
        explanation: "VPNs hide your IP and encrypt communication over the internet.",
    },
    {
        id: 25,
        topic: "CYBER HYGIENE", 
        color: "khaki",
        image: "CyberQuiz.Media/CyberQuiz.Media/questions_icons/ethics.png",
        question: "What is good cyber hygiene?",
        options: ["Regularly updating and securing devices","Keeping old software","Using default passwords","Ignoring notifications"],
        difficulty: 35,
        hint: "Think of it like digital cleanliness.",
        explanation: "Regular updates, antivirus use, and backups ensure safe computing.",
    },
    {
        id: 26,
        topic: "MALWARE", 
        color: "lightgreen",
        image: "CyberQuiz.Media/CyberQuiz.Media/questions_icons/ethics.png",
        question: "What type of malware disguises itself as legitimate software?",
        options: ["Trojan horse","Worm","Spyware","Ransomware"],
        difficulty: 45,
        hint: "Think of something that tricks you into installing it.",
        explanation: "A Trojan horse appears as legitimate software but secretly performs malicious actions.",
    },
    {
        id: 27,
        topic: "SOCIAL ENGINEERING", 
        color: "plum",
        image: "CyberQuiz.Media/CyberQuiz.Media/questions_icons/ethics.png",
        question: "What is the main goal of social engineering attacks?",
        options: ["Manipulate people to reveal confidential information","Steal physical devices","Install antivirus software","Encrypt harmless files"],
        difficulty: 55,
        hint: "It targets human psychology, not computers directly.",
        explanation: "Social engineering manipulates people into giving away confidential information or access.",
    },
    {
        id: 28,
        topic: "PASSWORDS", 
        color: "skyblue",
        image: "CyberQuiz.Media/CyberQuiz.Media/questions_icons/ethics.png",
        question: "Why is using the same password for multiple accounts risky?",
        options: ["A breach in one account can compromise others","It helps hackers guess your PIN","It reduces password length","It confuses login systems"],
        difficulty: 35,
        hint: "One leak can lead to many breaches.",
        explanation: "If one password is compromised, attackers can access all other accounts using the same one.",
    },
    {
        id: 29,
        topic: "PHISHING", 
        color: "firebrick",
        image: "CyberQuiz.Media/CyberQuiz.Media/questions_icons/ethics.png",
        question: "Which URL is most likely to be part of a phishing attempt?",
        options: ["https://www.paypa1.com","https://www.paypal.com","https://www.bank.com/secure","https://accounts.google.com"],
        difficulty: 50,
        hint: "Look closely at the spelling.",
        explanation: "Phishers use slightly altered URLs like 'paypa1.com' to deceive users.",
    },
    {
        id: 30,
        topic: "RANSOMWARE", 
        color: "darkred",
        image: "CyberQuiz.Media/CyberQuiz.Media/questions_icons/ethics.png",
        question: "What does ransomware typically demand from victims?",
        options: ["A payment to regain data access","A software update","A password reset","A security key"],
        difficulty: 60,
        hint: "It locks your files and asks for something in return.",
        explanation: "Ransomware encrypts files and demands a ransom for their decryption.",
    },
    {
        id: 31,
        topic: "EMAIL SECURITY", 
        color: "orchid",
        image: "CyberQuiz.Media/CyberQuiz.Media/questions_icons/ethics.png",
        question: "What should you do if you receive a suspicious email attachment?",
        options: ["Do not open it and verify with the sender","Open it immediately to check","Reply asking for details","Forward it to friends"],
        difficulty: 25,
        hint: "Be cautious with attachments.",
        explanation: "Opening suspicious attachments may activate malware. Always verify the sender first.",
    },
    {
        id: 32,
        topic: "WI-FI SECURITY", 
        color: "teal",
        image: "CyberQuiz.Media/CyberQuiz.Media/questions_icons/ethics.png",
        question: "Which Wi-Fi network should you avoid for sensitive activities?",
        options: ["Public Wi-Fi without encryption","Home network with WPA3","Office network with firewall","Secured mobile hotspot"],
        difficulty: 40,
        hint: "It’s open and easy to intercept.",
        explanation: "Public, unencrypted Wi-Fi can be easily monitored by attackers.",
    },
    {
        id: 33,
        topic: "UPDATES", 
        color: "limegreen",
        image: "CyberQuiz.Media/CyberQuiz.Media/questions_icons/ethics.png",
        question: "Why is keeping your software updated important for security?",
        options: ["Updates patch security vulnerabilities","It increases computer speed","It improves visuals","It changes the interface"],
        difficulty: 30,
        hint: "Think about fixing weaknesses.",
        explanation: "Software updates often contain patches for known security flaws.",
    },
    {
        id: 34,
        topic: "PASSWORDS", 
        color: "royalblue",
        image: "CyberQuiz.Media/CyberQuiz.Media/questions_icons/ethics.png",
        question: "What is a password manager used for?",
        options: ["Storing and generating strong passwords","Sharing passwords safely","Bypassing login pages","Hiding passwords from browsers"],
        difficulty: 35,
        hint: "It helps you manage multiple strong passwords.",
        explanation: "Password managers store and create unique, complex passwords securely.",
    },
    {
        id: 35,
        topic: "MALWARE", 
        color: "darkcyan",
        image: "CyberQuiz.Media/CyberQuiz.Media/questions_icons/ethics.png",
        question: "Which type of malware spreads automatically without user interaction?",
        options: ["Worm","Trojan","Spyware","Adware"],
        difficulty: 50,
        hint: "It crawls across systems on its own.",
        explanation: "A worm replicates and spreads without any user action.",
    },
    {
        id: 36,
        topic: "PHISHING", 
        color: "crimson",
        image: "CyberQuiz.Media/CyberQuiz.Media/questions_icons/ethics.png",
        question: "Which of the following is NOT a sign of a phishing email?",
        options: ["Proper grammar and official sender domain","Urgent request for personal info","Suspicious links","Unexpected attachments"],
        difficulty: 55,
        hint: "Professional emails look legitimate.",
        explanation: "Phishing emails often contain errors or fake domains; legitimate ones look official.",
    },
    {
        id: 37,
        topic: "MOBILE SECURITY", 
        color: "sienna",
        image: "CyberQuiz.Media/CyberQuiz.Media/questions_icons/ethics.png",
        question: "Why should you avoid installing apps from unknown sources?",
        options: ["They may contain malware","They’re slower","They’re not optimized","They take more storage"],
        difficulty: 40,
        hint: "They might not be safe.",
        explanation: "Unverified apps can contain malware or malicious code.",
    },
    {
        id: 38,
        topic: "BACKUPS", 
        color: "lightcoral",
        image: "CyberQuiz.Media/CyberQuiz.Media/questions_icons/ethics.png",
        question: "Why should backups be stored offline or in the cloud?",
        options: ["To protect against ransomware attacks","To reduce internet speed","To delete old data","To make files smaller"],
        difficulty: 60,
        hint: "They prevent data loss during attacks.",
        explanation: "Offline or cloud backups ensure data recovery even after ransomware infection.",
    },
    {
        id: 39,
        topic: "SOCIAL MEDIA", 
        color: "darkviolet",
        image: "CyberQuiz.Media/CyberQuiz.Media/questions_icons/ethics.png",
        question: "Why should you limit the personal information you post online?",
        options: ["It can be used for identity theft","It makes your profile less attractive","It lowers followers","It affects ads"],
        difficulty: 45,
        hint: "Attackers love oversharing.",
        explanation: "Excess personal data can be exploited for phishing or social engineering.",
    },
    {
        id: 40,
        topic: "FIREWALL", 
        color: "forestgreen",
        image: "CyberQuiz.Media/CyberQuiz.Media/questions_icons/ethics.png",
        question: "What is the main function of a firewall?",
        options: ["To block unauthorized network traffic","To speed up downloads","To encrypt passwords","To delete viruses"],
        difficulty: 30,
        hint: "It filters traffic between networks.",
        explanation: "A firewall monitors and controls incoming and outgoing network traffic.",
    },
    {
        id: 41,
        topic: "ENCRYPTION", 
        color: "goldenrod",
        image: "CyberQuiz.Media/CyberQuiz.Media/questions_icons/ethics.png",
        question: "What does encryption do?",
        options: ["Converts data into a code to prevent unauthorized access","Deletes unneeded files","Compresses data","Changes file names"],
        difficulty: 50,
        hint: "It protects information by scrambling it.",
        explanation: "Encryption secures data by making it unreadable without a decryption key.",
    },
    {
        id: 42,
        topic: "BROWSER SECURITY", 
        color: "steelblue",
        image: "CyberQuiz.Media/CyberQuiz.Media/questions_icons/ethics.png",
        question: "What does the padlock icon in a browser’s address bar mean?",
        options: ["The website uses HTTPS encryption","The site has no popups","It’s safe from phishing","It’s government verified"],
        difficulty: 35,
        hint: "It’s about secure connections.",
        explanation: "The padlock icon indicates that the site uses HTTPS and encrypts communication.",
    },
    {
        id: 43,
        topic: "VPN", 
        color: "mediumslateblue",
        image: "CyberQuiz.Media/CyberQuiz.Media/questions_icons/ethics.png",
        question: "What does a VPN primarily do?",
        options: ["Encrypts your internet traffic and hides your IP address","Increases internet speed","Blocks all ads","Saves passwords"],
        difficulty: 40,
        hint: "It’s used for secure, private browsing.",
        explanation: "A VPN hides your IP and encrypts traffic to ensure online privacy.",
    },
    {
        id: 44,
        topic: "INSIDER THREATS", 
        color: "darkmagenta",
        image: "CyberQuiz.Media/CyberQuiz.Media/questions_icons/ethics.png",
        question: "Who can be an insider threat?",
        options: ["A current or former employee misusing access","A random hacker","A malware bot","A system admin"],
        difficulty: 70,
        hint: "They already have legitimate access.",
        explanation: "Insider threats come from trusted individuals abusing their access.",
    },
    {
        id: 45,
        topic: "CLOUD SECURITY", 
        color: "darkorange",
        image: "CyberQuiz.Media/CyberQuiz.Media/questions_icons/ethics.png",
        question: "What is a major security concern with cloud storage?",
        options: ["Data breaches due to weak access controls","Too much free space","Slow uploads","Limited storage"],
        difficulty: 60,
        hint: "Think of unauthorized access to your files.",
        explanation: "Improper access management in cloud systems can lead to data leaks.",
    },
    {
        id: 46,
        topic: "IOT SECURITY", 
        color: "mediumseagreen",
        image: "CyberQuiz.Media/CyberQuiz.Media/questions_icons/ethics.png",
        question: "Why are smart home devices vulnerable to attacks?",
        options: ["They often lack strong security measures","They have strong encryption","They are disconnected from networks","They’re too expensive to hack"],
        difficulty: 65,
        hint: "Many IoT devices skip updates.",
        explanation: "Weak security configurations make IoT devices easy to exploit.",
    },
    {
        id: 47,
        topic: "PHISHING", 
        color: "tomato",
        image: "CyberQuiz.Media/CyberQuiz.Media/questions_icons/ethics.png",
        question: "What is 'spear phishing'?",
        options: ["A targeted phishing attack aimed at a specific person","Random spam messages","Physical data theft","Malware installed on phones"],
        difficulty: 70,
        hint: "It’s a focused attack, not random.",
        explanation: "Spear phishing targets specific individuals using personalized information.",
    },
    {
        id: 48,
        topic: "TWO-FACTOR AUTHENTICATION", 
        color: "orchid",
        image: "CyberQuiz.Media/CyberQuiz.Media/questions_icons/ethics.png",
        question: "What’s the benefit of two-factor authentication (2FA)?",
        options: ["Adds an extra layer of security beyond passwords","Makes logins faster","Disables old passwords","Removes password need"],
        difficulty: 30,
        hint: "It’s about adding an extra verification step.",
        explanation: "2FA combines something you know (password) with something you have (code/device).",
    },
    {
        id: 49,
        topic: "CYBER ETHICS", 
        color: "saddlebrown",
        image: "CyberQuiz.Media/CyberQuiz.Media/questions_icons/ethics.png",
        question: "Why is it important to practice ethical behavior online?",
        options: ["It builds trust and prevents legal issues","It helps hackers","It slows down servers","It hides your identity"],
        difficulty: 25,
        hint: "Think about online responsibility.",
        explanation: "Ethical online behavior ensures safety, trust, and respect for others’ privacy.",
    },
    {
        id: 50,
        topic: "INCIDENT RESPONSE", 
        color: "gray",
        image: "CyberQuiz.Media/CyberQuiz.Media/questions_icons/ethics.png",
        question: "What should you do first after detecting a cyber incident?",
        options: ["Report it to the security team immediately","Try to delete files","Ignore and continue working","Disconnect from internet permanently"],
        difficulty: 80,
        hint: "Don’t act alone; involve professionals.",
        explanation: "Quick reporting helps containment and minimizes damage.",
    }
];